### ISSUE TITLE
DLJC -- add target jar to output information

### ISSUE THREAD

**Issue by joecox** [SRI-CSL/pascali-public#6]
It would be helpful to see the target jar in the output information of the `print` tool.  For example, when running dljc on https://github.com/petablox-project/petablox, I run `ant clean compile`.  I get as output the classpath 

```
'classpath': '/path/classes:/path/lib/joeq.jar:/path/lib/jwutil.jar:/path/lib/jdom.jar:
/path/lib/bddbddb.jar:/path/lib/javabdd-1.0b2.jar:/path/lib/javassist.jar:/path/lib/hj.jar:
/path/lib/CnCHj.jar:/path/lib/trove-3.0.2.jar:/path/lib/scannotation-1.0.2.jar:/path/lib/j2h.jar:
/path/lib/saxon9.jar:/path/lib/soot-trunk.jar:/path/lib/confspellcheck-0.1.jar'
```

which is very helpful, but I don't get any information that the target jar that is built is at `/path/petablox.jar`

**Comment by joecox** [comment]
Also information about the main class would be nice.

**Comment by tim-mccarthy** [comment]
Done! DLJC now captures jar creation by ant and maven (it doesn't seem to be possible to do it for gradle in any generic way, and obviously plain old javac doesn't make jars).

**Comment by joecox** [comment]
This is great, thank you!
